### ISSUE TITLE
1.0 Schematic

### ISSUE THREAD

**Issue by thejpster** [Neotron-Compute/Neotron-32-Hardware#1]

**Comment by thejpster** [comment]
Schematic completed. Needs review and footprints allocating.

**Comment by thejpster** [comment]
v0.7.0 is up for review.

**Comment by IGBC** [comment]
Yes looks good to me

**Comment by thejpster** [comment]
For completeness I issued 0.8.0 today. On the schematic side it just swaps two PS/2 sockets for one double socket.

**Comment by thejpster** [comment]
I'm now allocating part numbers so we can place an order on Octopart using the metadata in the schematic.

**Comment by thejpster** [comment]
Commit and be damned. v1.2.0 out for manufacture.
