### ISSUE TITLE
LDO holes too small

### ISSUE THREAD

**Issue by thejpster** [Neotron-Compute/Neotron-32-Hardware#21]
The LDO legs have little kinks in them. The holes are too small, so you can't get the LDO flush to the board. Maybe that's OK?

**Comment by jonathanpallant** [comment]
Maybe we should leave space so the LDO can lay down flat on the PCB. Might be a bit more robust for transport/shipping.

**Comment by thejpster** [comment]
Or we could make space to lay the LDO down flat. You'd have to bend the leads, or get one with bent leads.
