### ISSUE TITLE
faulty schematic for audio section in Release 0.6

### ISSUE THREAD

**Issue by IGBC** [Neotron-Compute/Neotron-32-Hardware#9]
Audio connectors are wired incorrectly in the 0.6 schematic. 

Band-pass audio filter also looks suspect, and should be reviewed.

**Comment by thejpster** [comment]
It's a straight copy of the Monotron schematic, which as far as I know, works fine. Any differences from that would be a bug. The low pass filter is the same as the Raspberry Pi Zero.

**Comment by thejpster** [comment]
Are you happy with the audio circuit as-is or does it need changing?
